// 错误码配置
export const ERROR_CODES = {
  API_ERROR: 'API_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  STREAM_ERROR: 'STREAM_ERROR',
};

// 错误消息配置
export const ERROR_MESSAGES = {
  [ERROR_CODES.API_ERROR]: 'API调用失败',
  [ERROR_CODES.NETWORK_ERROR]: '网络请求失败',
  [ERROR_CODES.TIMEOUT]: '请求超时，请稍后重试',
  [ERROR_CODES.UNAUTHORIZED]: '未授权，请提供有效的API密钥',
  [ERROR_CODES.INVALID_RESPONSE]: '响应格式无效',
  [ERROR_CODES.STREAM_ERROR]: '无法获取响应流',
};
